version: "3.7"

networks:
  default:
    external:
      name: gateway

services:
  pgsql:
    image: postgres:latest
    container_name: postgresql
    restart: unless-stopped
    env_file: .env
    ports:
      - "5442:5432"
    volumes:
      - pgsql-db:/var/lib/postgresql/data
    networks:
      - default

  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    env_file: .env
    ports:
      - "3030:80"
    networks:
      - default

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: "iamaul/fatbellies-api-node:latest"
    container_name: app
    restart: unless-stopped
    depends_on: 
      - pgsql
    links:
      - pgsql
    networks:
      - default
    env_file: .env
    environment:
      - PORT=${PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_NAME}
    ports:
      - "5000:5000"

volumes:
  pgsql-db:
